

services:
  source_postgres:
    image: postgres:15
    ports:
      - '5433:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  destination_postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elt_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ['python', 'elt_script.py']
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"


  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command: [
      "run",
      "--profiles-dir",
      "/root",
      "--project-dir",
      "/dbt",
    ]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: custom_postgres
      DBT_TARGET: dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  elt_network:
    driver: bridge
